---
# tasks file for secondrole
- name: Remove nginx cleanly (if broken)
  ansible.builtin.apt:
    name: "{{ webserver_packages[webserver_type] }}"
    state: absent
    purge: yes
    force_apt_get: yes

- name: Clean apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install web server
  ansible.builtin.apt:
    name: "{{ webserver_packages[webserver_type] }}"
    state: present
    force_apt_get: yes
    
- name: Start web server
  ansible.builtin.service:
    name: "{{ webserver_packages[webserver_type] }}"
    state: started
    enabled: yes

- name: Dummy change to force restart
  ansible.builtin.command: echo "forcing restart"
  notify: restart_webserver